packages:
  - apps/*
  - packages/*

catalog:
  '@happy-dom/global-registrator': 20.5.3
  '@tsconfig/node24': 24.0.4
  '@types/bun': 1.3.8
  '@types/node': 24.10.12
  '@typescript/native-preview': 7.0.0-dev.20260210.1
  eslint: 10.0.0
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-unused-imports: 4.4.1
  oxfmt: 0.28.0
  oxlint: 1.43.0
  oxlint-tsgolint: 0.11.5
  typescript: 5.9.3
  typescript-eslint: 8.55.0
  unplugin-dts: 1.0.0-beta.6
  vite: 8.0.0-beta.13

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@miyaoka/vite-plugin-doc-block'

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - unrs-resolver
  - vue-demi
