packages:
  - packages/*

catalog:
  '@tsconfig/node24': 24.0.4
  '@types/bun': 1.3.7
  typescript: 5.9.3

minimumReleaseAge: 4320

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - unrs-resolver
  - vue-demi
