packages:
  - packages/*
  - services/*

catalog:
  '@happy-dom/global-registrator': 20.4.0
  '@tsconfig/node24': 24.0.4
  '@types/bun': 1.3.7
  '@types/node': 24.10.9
  eslint: 9.39.2
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-unused-imports: 4.3.0
  typescript: 5.9.3
  typescript-eslint: 8.54.0
  unplugin-dts: 1.0.0-beta.6
  vite: 8.0.0-beta.11

minimumReleaseAge: 4320

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - unrs-resolver
  - vue-demi
