packages:
  - apps/*
  - packages/*

catalog:
  '@happy-dom/global-registrator': 20.7.0
  '@tsconfig/node24': 24.0.4
  '@types/bun': 1.3.9
  '@types/node': 24.10.13
  '@typescript/native-preview': 7.0.0-dev.20260224.1
  eslint: 10.0.2
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-unused-imports: 4.4.1
  oxfmt: 0.35.0
  oxlint: 1.50.0
  oxlint-tsgolint: 0.14.2
  typescript: 5.9.3
  typescript-eslint: 8.56.1
  unplugin-dts: 1.0.0-beta.6
  vite: 8.0.0-beta.15

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@miyaoka/vite-plugin-doc-block'

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - unrs-resolver
  - vue-demi
